# Generated by Django 4.1.5 on 2023-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerscount',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='followerscount',
            name='following',
        ),
        migrations.AddField(
            model_name='followerscount',
            name='follower',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
